const items = [
    {
        id: '001',
        image:'id001image.jpeg',
        company: 'Kérastase Chroma Absolu Bain ',
        item_name: 'Riche Chroma Shampoo 250ml',
        original_price: 2650,
        current_price: 1113,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '002id.jpg',
        company: 'Kérastase Chroma Absolu Bain ',
        item_name: 'Chroma Respect Shampoo 250ml',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'id003image.jpeg',
        company: 'Kérastase Chroma Absolu Bain',
        item_name: 'Vital Dermo Calm 250 ML',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },

    {
        id: '004',
        image: 'id004image.jpeg',
        company: 'Kérastase Chroma Absolu Bain',
            item_name: ' Homme 250ML D47',
            original_price: 999,
            current_price: 999,
            discount_percentage: 0,
            return_period: 14,
            delivery_date: '10 Oct 2024',
            rating: {
                stars: 5.0,
                count: 10,
            },
        },
    {
        id: '005',
        image: '002id.jpg',
        company: 'Kérastase Chroma Absolu Bain ',
        item_name: 'Chroma Respect Shampoo 250ml',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '006',
        image: '002id.jpg',
        company: 'Kérastase Chroma Absolu Bain ',
        item_name: 'Chroma Respect Shampoo 250ml',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
 
   
   
    {
        id: '007',
        image: 'id003image.jpeg',
        company: 'L’Oréal Professionnel ',
        item_name: 'Hair Color Pure Shampoo 250 ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },

    {
        id: '008',
        image: 'id004image.jpeg',
        company: 'L’Oréal Professionnel ',
        item_name: 'AC Anti-Dandruff Shampoo 250ml',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
   
];